[package]
name = "oberth"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2

[dependencies]
shipyard = "0.5"
vek = "0.15"

[dev-dependencies]
kiss3d = "0.33"
rand = "0.8"
plotters = "0.3"
